# Generated by Django 4.2.4 on 2023-08-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
